logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecdb
    username: okuya
    password: 0627
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
